--------------------------------------------------------
--  File created - Friday-December-10-2021   
--------------------------------------------------------
REM INSERTING into ADMIN.MANAGEMENT_COMPANY
SET DEFINE OFF;
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (1,'1010data, Inc.','Barnesville','56 Roxbury Crossing','NY','14724',2123769125,'www.1010data.com',to_date('01-FEB-78','DD-MON-RR'),to_date('01-FEB-28','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (2,'10gen, Inc.','Eastlake','56 Mission Hill','PA','19038',2152549594,'www.10gen.com',to_date('04-JUN-78','DD-MON-RR'),to_date('04-JUN-26','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (3,'Actian Corp.','Tipton','25 York Road','MD','21056',2407484111,'www.ActianCorp.com',to_date('19-JAN-78','DD-MON-RR'),to_date('19-JAN-27','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (4,'Ingres Corp.','Tampa','79 School Lane','VA','24270',2367515963,'www.IngresCorp.com',to_date('28-MAY-78','DD-MON-RR'),to_date('28-MAY-32','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (5,'Informatica Company','Roaring River','96 Broadway','NY','12306',2122684076,'www.Informatica Company.com',to_date('28-JAN-78','DD-MON-RR'),to_date('28-JAN-29','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (6,'AddressDoctor','Lucas','85 South Street','CA','93662',2099843789,'www.AddressDoctor.com',to_date('21-JAN-78','DD-MON-RR'),to_date('21-JAN-24','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (7,'Aerospike, Inc.','Richmond','15 Park Lane','CA','95353',2095500139,'www.Aerospike, Inc..com',to_date('25-FEB-78','DD-MON-RR'),to_date('25-FEB-26','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (8,'Citrusleaf','Oxford','239 George Street','OH','44243',2169003642,'www.Citrusleaf.com',to_date('07-APR-78','DD-MON-RR'),to_date('07-APR-31','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (9,'Alteryx, Inc.','Albright','84 Manor Road','NY','11480',2123898573,'www.Alteryx.com',to_date('29-JUN-78','DD-MON-RR'),to_date('29-JUN-29','DD-MON-RR'));
Insert into ADMIN.MANAGEMENT_COMPANY (M_ID,M_NAME,M_CITY,M_STREET,M_STATE,M_ZIPCODE,M_CONTACT,M_WEBSITEURL,M_STARTDATE,M_ENDDATE) values (10,'SRC','Tuppers Plains','37 Grove Road','TN','38580',4233553751,'www.SRC.com',to_date('02-NOV-78','DD-MON-RR'),to_date('02-NOV-31','DD-MON-RR'));
