CREATE OR REPLACE PROCEDURE CREATE_TABLES
IS

nCount NUMBER;

BEGIN

SELECT count(*) into nCount FROM user_tables where table_name = 'MANAGEMENT_COMPANY';
IF(nCount > 0)

THEN 

EXECUTE IMMEDIATE 'Drop table MANAGEMENT_COMPANY';

ELSE

EXECUTE IMMEDIATE 'CREATE TABLE MANAGEMENT_COMPANY(M_ID NUMBER(10) PRIMARY KEY,
M_NAME VARCHAR(30) NOT NULL,
M_CITY VARCHAR(30) NOT NULL,
M_STREET VARCHAR(30) NOT NULL,
M_STATE VARCHAR(30) NOT NULL,
M_ZIPCODE VARCHAR(5) NOT NULL,
M_CONTACT NUMBER(10) NOT NULL UNIQUE,
M_WEBSITEURL VARCHAR(50) NOT NULL,
M_STARTDATE DATE NOT NULL,
M_ENDDATE DATE NOT NULL)';

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'EMPLOYEE';
IF(nCount > 0)

THEN

EXECUTE IMMEDIATE 'Drop table EMPLOYEE';

ELSE

EXECUTE IMMEDIATE 'CREATE TABLE EMPLOYEE(E_ID NUMBER(10) PRIMARY KEY,
fk_M_ID NUMBER(10) NOT NULL CONSTRAINT fk_M_ID references MANAGEMENT_COMPANY(M_ID),
E_FIRST_NAME VARCHAR(20) NOT NULL,
E_LAST_NAME VARCHAR(20) NOT NULL,
E_CONTACT NUMBER(10) NOT NULL UNIQUE,
E_CITY VARCHAR(30) NOT NULL,
E_STREET VARCHAR(30) NOT NULL,
E_STATE VARCHAR(30) NOT NULL,
E_ZIPCODE VARCHAR(5) NOT NULL,
E_SALARY NUMBER(8,2) NOT NULL,
E_DESIGNATION VARCHAR(30) NOT NULL,
E_HIRE_DATE DATE NOT NULL,
E_DOB DATE NOT NULL,
E_EMAIL VARCHAR(50) NOT NULL UNIQUE,
E_SSN NUMBER(10) NOT NULL,
E_GENDER VARCHAR(10) NOT NULL)';
END IF;



END;
