CALL delete_entity('CUSTOMER_BANK_DETAIL','TABLE');

CREATE TABLE CUSTOMER_BANK_DETAIL(DETAIL_ID NUMBER(10) PRIMARY KEY,fk_CBD_C_ID NUMBER(10) NOT NULL CONSTRAINT fk_CBD_C_ID references CUSTOMER(C_ID),BANKNAME VARCHAR(30) NOT NULL,ACCOUNT_NUMBER NUMBER NOT NULL, 
BANK_ROUTINGNUMBER NUMBER NOT NULL,LAST_UPDATED DATE NOT NULL);

CALL delete_entity('CUSTOMER_CARD_DETAIL','TABLE');

CREATE TABLE CUSTOMER_CARD_DETAIL(CARD_NUMBER NUMBER PRIMARY KEY,fk_C_ID NUMBER(10) NOT NULL CONSTRAINT fk_C_ID references CUSTOMER(C_ID),EXPIRY_DATE DATE NOT NULL,CARD_TYPE VARCHAR(15) NOT NULL, 
NAME_ON_CARD VARCHAR(30) NOT NULL,CVV NUMBER(4) NOT NULL);

CALL delete_entity('UTILITY','TABLE');

CREATE TABLE UTILITY(U_ID NUMBER(10) PRIMARY KEY,fk_UTILITY_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_UTILITY_P_ID references PROPERTY(P_ID),UTILITY_TYPE VARCHAR(10) NOT NULL,AVAILABILITY VARCHAR(1) NOT NULL);

CALL delete_entity('FEEDBACK','TABLE');

CREATE TABLE FEEDBACK(F_ID NUMBER(10) PRIMARY KEY,fk_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_P_ID references PROPERTY(P_ID),F_DESCRIPTION VARCHAR(255) NOT NULL, F_RATING_MAINTAINANCE NUMBER(1) NOT NULL,
F_RATING_CLEANLINESS NUMBER(1) NOT NULL,F_RATING_AMENITIES NUMBER(1) NOT NULL,F_RATING_UTILITIES NUMBER(1) NOT NULL,F_RATING_LOCATION NUMBER(1) NOT NULL,F_RATING_RENT NUMBER(1) NOT NULL,
F_RATING_APTCONDITION NUMBER(1) NOT NULL,F_RATING_RECOMMENDATION NUMBER(1) NOT NULL,F_DATE DATE NOT NULL);

CALL delete_entity('COMPLAINT','TABLE');

CREATE TABLE COMPLAINT(COMP_ID NUMBER(10) PRIMARY KEY,fk_COMPLAINT_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_COMPLAINT_P_ID references PROPERTY(P_ID) ,fk_COMP_TYPE_ID NUMBER(10) NOT NULL CONSTRAINT fk_COMP_TYPE_ID references COMPLAINT_TYPE(COMP_TYPE_ID), 
C_DATE DATE NOT NULL, C_STATUS VARCHAR(20) NOT NULL,COMP_DESC VARCHAR(255) NOT NULL,COMP_SEVERITY VARCHAR(10) NOT NULL,COMP_PRIORITY NUMBER(2) NOT NULL);

CALL delete_entity('COMPLAINT_TYPE','TABLE');

CREATE TABLE COMPLAINT_TYPE(COMP_TYPE_ID NUMBER(10) PRIMARY KEY,COMP_TYPE VARCHAR(20) NOT NULL);


