CALL delete_entity('CUSTOMER_BANK_DETAIL','TABLE');

CALL delete_entity('CUSTOMER_CARD_DETAIL','TABLE');

CALL delete_entity('UTILITY','TABLE');

CALL delete_entity('FEEDBACK','TABLE');

CALL delete_entity('COMPLAINT','TABLE');

CALL delete_entity('COMPLAINT_TYPE','TABLE');

CALL delete_entity('LEASE','TABLE');

CALL delete_entity('PROPERTY','TABLE');

CALL delete_entity('CUSTOMER','TABLE');

CALL delete_entity('OWNER','TABLE');

CALL delete_entity('EMPLOYEE','TABLE');

CALL delete_entity('MANAGEMENT_COMPANY','TABLE');


CREATE TABLE MANAGEMENT_COMPANY(M_ID NUMBER(10) PRIMARY KEY,M_NAME VARCHAR(30) NOT NULL,M_CITY VARCHAR(30) NOT NULL,M_STREET VARCHAR(30) NOT NULL,M_STATE VARCHAR(30) NOT NULL,
M_ZIPCODE VARCHAR(5) NOT NULL,M_CONTACT NUMBER(10) NOT NULL UNIQUE,M_WEBSITEURL VARCHAR(50) NOT NULL,M_STARTDATE DATE NOT NULL,M_ENDDATE DATE NOT NULL);


CREATE TABLE EMPLOYEE(E_ID NUMBER(10) PRIMARY KEY,fk_M_ID NUMBER(10) NOT NULL CONSTRAINT fk_M_ID references MANAGEMENT_COMPANY(M_ID),E_FIRST_NAME VARCHAR(20) NOT NULL,E_LAST_NAME VARCHAR(20) NOT NULL,E_CONTACT NUMBER(10) NOT NULL UNIQUE,
E_CITY VARCHAR(30) NOT NULL,E_STREET VARCHAR(30) NOT NULL,E_STATE VARCHAR(30) NOT NULL,E_ZIPCODE VARCHAR(5) NOT NULL,E_SALARY NUMBER(8,2) NOT NULL,E_DESIGNATION VARCHAR(30) NOT NULL,
E_HIRE_DATE DATE NOT NULL,E_DOB DATE NOT NULL,E_EMAIL VARCHAR(50) NOT NULL UNIQUE,E_SSN NUMBER(10) NOT NULL,E_GENDER VARCHAR(10) NOT NULL);


CREATE TABLE OWNER(O_ID NUMBER(10) PRIMARY KEY, O_FNAME VARCHAR(20) NOT NULL, O_LNAME VARCHAR(20) NOT NULL, O_DOB DATE NOT NULL, O_STREET VARCHAR(30) NOT NULL, O_CITY VARCHAR(30) NOT NULL,
O_STATE VARCHAR(30) NOT NULL,O_ZIPCODE NUMBER(5) NOT NULL,O_CONTACT NUMBER(10) NOT NULL,O_SSN NUMBER(10) UNIQUE NOT NULL,O_DATE_ADDED DATE NOT NULL,O_EMAIL VARCHAR(50) NOT NULL,O_GENDER VARCHAR(10) NOT NULL,
O_OCCUPATION VARCHAR(30) NOT NULL);



CREATE TABLE CUSTOMER(C_ID NUMBER(10) PRIMARY KEY,C_FNAME VARCHAR(20) NOT NULL,C_LNAME VARCHAR(20) NOT NULL,C_PHONE NUMBER(10) NOT NULL UNIQUE,
C_EMAIL VARCHAR(20) NOT NULL UNIQUE,C_DOB DATE NOT NULL,C_CITY VARCHAR(30) NOT NULL,C_STREET VARCHAR(30) NOT NULL,C_STATE VARCHAR(30) NOT NULL,
C_ZIPCODE VARCHAR(5) NOT NULL,C_RFNAME VARCHAR(20) NOT NULL,C_RLNAME VARCHAR(20) NOT NULL,C_REFRELATION VARCHAR(10) NOT NULL,C_REFPHONE VARCHAR(10) NOT NULL,
C_REFADDRESS VARCHAR(40) NOT NULL,C_DATE_ADDED DATE NOT NULL,C_SSN NUMBER(10) NOT NULL,C_OCCUPATION VARCHAR(30) NOT NULL,C_GENDER VARCHAR(10) NOT NULL);



CREATE TABLE PROPERTY(P_ID NUMBER(10) PRIMARY KEY,fk_M_ID NUMBER(10) NOT NULL CONSTRAINT fk_M_ID references MANAGEMENT_COMPANY(M_ID),fk_O_ID NUMBER(10) NOT NULL CONSTRAINT fk_O_ID references OWNER(O_ID),P_TYPE VARCHAR(20) NOT NULL,P_CITY VARCHAR(30) NOT NULL,
P_STREET VARCHAR(30) NOT NULL,P_STATE VARCHAR(30) NOT NULL,P_ZIPCODE VARCHAR(5) NOT NULL,P_DESCRIPTION VARCHAR(500) NOT NULL,P_CONFIGURATION VARCHAR(10) NOT NULL,
P_DISCOUNT NUMBER(7,2) NOT NULL,P_DATE_LISTED DATE NOT NULL,P_FLOOR NUMBER(4) NOT NULL,P_CARPETAREA NUMBER(6,2) NOT NULL);


CREATE TABLE LEASE(L_ID NUMBER(10) PRIMARY KEY,fk_LEASE_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_LEASE_P_ID references PROPERTY(P_ID),fk_LEASE_C_ID NUMBER(10) NOT NULL CONSTRAINT fk_LEASE_C_ID references CUSTOMER(C_ID),L_STRTDATE DATE NOT NULL, L_ENDDATE DATE NOT NULL, L_STATUS VARCHAR(15) NOT NULL, MON_RENT NUMBER(7,2) NOT NULL,
LEASE_BREAK_DATE DATE,L_PAY_DUEDATE DATE NOT NULL,DEPOSIT NUMBER(7,2) NOT NULL,KEYFEE NUMBER(7,2) NOT NULL,APPLICATION_FEE NUMBER(7,2) NOT NULL,LATEFEE NUMBER(7,2) NOT NULL,
MISC NUMBER(7,2) NOT NULL,SUBLEASING_ALLOWED VARCHAR(10) NOT NULL);

CREATE TABLE COMPLAINT_TYPE(COMP_TYPE_ID NUMBER(10) PRIMARY KEY,COMP_TYPE VARCHAR(20) NOT NULL);


CREATE TABLE COMPLAINT(COMP_ID NUMBER(10) PRIMARY KEY,fk_COMPLAINT_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_COMPLAINT_P_ID references PROPERTY(P_ID) ,fk_COMP_TYPE_ID NUMBER(10) NOT NULL CONSTRAINT fk_COMP_TYPE_ID references COMPLAINT_TYPE(COMP_TYPE_ID), 
C_DATE DATE NOT NULL, C_STATUS VARCHAR(20) NOT NULL,COMP_DESC VARCHAR(255) NOT NULL,COMP_SEVERITY VARCHAR(10) NOT NULL,COMP_PRIORITY NUMBER(2) NOT NULL);


CREATE TABLE FEEDBACK(F_ID NUMBER(10) PRIMARY KEY,fk_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_P_ID references PROPERTY(P_ID),F_DESCRIPTION VARCHAR(255) NOT NULL, F_RATING_MAINTAINANCE NUMBER(1) NOT NULL,
F_RATING_CLEANLINESS NUMBER(1) NOT NULL,F_RATING_AMENITIES NUMBER(1) NOT NULL,F_RATING_UTILITIES NUMBER(1) NOT NULL,F_RATING_LOCATION NUMBER(1) NOT NULL,F_RATING_RENT NUMBER(1) NOT NULL,
F_RATING_APTCONDITION NUMBER(1) NOT NULL,F_RATING_RECOMMENDATION NUMBER(1) NOT NULL,F_DATE DATE NOT NULL);


CREATE TABLE UTILITY(U_ID NUMBER(10) PRIMARY KEY,fk_UTILITY_P_ID NUMBER(10) NOT NULL CONSTRAINT fk_UTILITY_P_ID references PROPERTY(P_ID),UTILITY_TYPE VARCHAR(10) NOT NULL,AVAILABILITY VARCHAR(1) NOT NULL);


CREATE TABLE CUSTOMER_CARD_DETAIL(CARD_NUMBER NUMBER PRIMARY KEY,fk_C_ID NUMBER(10) NOT NULL CONSTRAINT fk_C_ID references CUSTOMER(C_ID),EXPIRY_DATE DATE NOT NULL,CARD_TYPE VARCHAR(15) NOT NULL, 
NAME_ON_CARD VARCHAR(30) NOT NULL,CVV NUMBER(4) NOT NULL);


CREATE TABLE CUSTOMER_BANK_DETAIL(DETAIL_ID NUMBER(10) PRIMARY KEY,fk_CBD_C_ID NUMBER(10) NOT NULL CONSTRAINT fk_CBD_C_ID references CUSTOMER(C_ID),BANKNAME VARCHAR(30) NOT NULL,ACCOUNT_NUMBER NUMBER NOT NULL, 
BANK_ROUTINGNUMBER NUMBER NOT NULL,LAST_UPDATED DATE NOT NULL);






