SET SERVEROUTPUT ON;

SELECT * FROM MANAGEMENT_COMPANY;
SELECT * FROM EMPLOYEE;
SELECT * FROM OWNER;
SELECT * FROM CUSTOMER;
SELECT * FROM PROPERTY;
SELECT * FROM LEASE;
SELECT * FROM CUSTOMER_BANK_DETAIL;
SELECT * FROM CUSTOMER_CARD_DETAIL; --- PUBLIC
SELECT * FROM CUSTOMER_PAYMENT;
SELECT * FROM FEEDBACK;
SELECT * FROM COMPLAINT; -- PUBLIC
SELECT * FROM COMPLAINT_TYPE;
SELECT * FROM UTILITY;
SELECT * FROM MEMBER_TYPE;

