
SET SERVEROUTPUT ON;

------VIEW ALL ACTIVE LEASES------
CREATE OR REPLACE VIEW ALL_LEASES AS
SELECT P.P_ID "PROPERTY ID", P.P_CITY "PROPERTY CITY", P.P_CONFIGURATION "CONFIGURATION",
L.L_ID "LEASE ID",  L.L_STATUS "LEASE STATUS", L.L_STRTDATE "LEASE START DATE",
L.L_ENDDATE "LEASE END DATE",
C.C_FNAME|| ' ' ||C.C_LNAME "CUSTOMER NAME",C.C_PHONE "PHONE NO",
C.C_EMAIL "EMAIL ID",C.C_CITY "CUSTOMER CITY"
FROM PROPERTY P JOIN LEASE L
ON P.P_ID = L.FK_P_ID
JOIN CUSTOMER C
ON  C.C_ID=L.FK_LEASE_C_ID
WHERE L.L_STATUS = "Active";

SELECT * FROM ALL_LEASES;

------VIEW ALL CUSTOMER PAYMENTS------
CREATE OR REPLACE VIEW ALL_COMPLAINTS AS
SELECT P.P_ID "PROPERTY ID", P.P_TYPE "PROPERTY TYPE", 
P.P_CONFIGURATION "CONFIGURATION", P.P_STREET "PROPERTY STREET",
P.P_CITY "PROPERTY CITY", C.COMP_ID "COMPLAINT ID",
C.C_DATE "COMPLAINT DATE", C.C_STATUS "COMPLAINT STATUS", 
C.COMP_PRIORITY "PRIORITY",
COMP.COMP_TYPE_ID
FROM PROPERTY P JOIN COMPLAINT C
ON P.P_ID = C.FK_PID
JOIN COMPLAINT_TYPE COMP
ON  C.FK_COMPTID=COMP.COMP_TYPE_ID;
SELECT * FROM ALL_COMPLAINTS;


--EXECUTE IMMEDIATE  'Insert into ADMIN.LEASE  values (17,17,17,to_date(''15-NOV-21'',''DD-MON-RR''),to_date(''15-NOV-22'',''DD-MON-RR''),''Active'',2500,null,to_date(''15-NOV-21'',''DD-MON-RR''),2500,30,75,200,50,''Yes'')';
--EXECUTE IMMEDIATE  'Insert into ADMIN.LEASE  values (18,18,18,to_date(''01-JUN-21'',''DD-MON-RR''),to_date(''01-JUN-22'',''DD-MON-RR''),''Active'',2500,null,to_date(''01-MAY-21'',''DD-MON-RR''),2500,30,75,200,50,''Yes'')';


EXECUTE IMMEDIATE  'Insert into ADMIN.LEASE  values (6,6,6,to_date(''10-NOV-12'',''DD-MON-RR''),to_date(''27-OCT-13'',''DD-MON-RR''),''Broken'',2800,to_date(''27-MAY-13'',''DD-MON-RR''),to_date(''10-OCT-12'',''DD-MON-RR''),2800,30,75,250,50,''No'')';