
SET SERVEROUTPUT ON;

------VIEW ALL LEASES------
CREATE OR REPLACE VIEW ALL_LEASES AS
SELECT P.P_ID "PROPERTY ID", P.P_CITY "PROPERTY CITY", P.P_CONFIGURATION "CONFIGURATION",
L.L_ID "LEASE ID",  L.L_STATUS "LEASE STATUS", L.L_STRTDATE "LEASE START DATE",
L.L_ENDDATE "LEASE END DATE",
C.C_FNAME|| ' ' ||C.C_LNAME "CUSTOMER NAME",C.C_PHONE "PHONE NO",
C.C_EMAIL "EMAIL ID",C.C_CITY "CUSTOMER CITY"
FROM PROPERTY P JOIN LEASE L
ON P.P_ID = L.FK_P_ID
JOIN CUSTOMER C
ON  C.C_ID=L.FK_LEASE_C_ID;

SELECT * FROM ALL_LEASES;

------VIEW ALL CUSTOMER PAYMENTS------
CREATE OR REPLACE VIEW ALL_COMPLAINTS AS
SELECT P.P_ID "PROPERTY ID", P.P_TYPE "PROPERTY TYPE", 
P.P_CONFIGURATION "CONFIGURATION", P.P_STREET "PROPERTY STREET",
P.P_CITY "PROPERTY CITY", C.COMP_ID "COMPLAINT ID",
C.C_DATE "COMPLAINT DATE", C.C_STATUS "COMPLAINT STATUS", 
C.COMP_PRIORITY "PRIORITY",
COMP.COMP_TYPE_ID
FROM PROPERTY P JOIN COMPLAINT C
ON P.P_ID = C.FK_PID
JOIN COMPLAINT_TYPE COMP
ON  C.FK_COMPTID=COMP.COMP_TYPE_ID;
SELECT * FROM ALL_COMPLAINTS;